# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Atelier-Icelf
name: 冰精工房
email: csxy010317jack@qq.com
location: 致远星
company: 睿站
company_url: https://space.bilibili.com/315312
github_url: https://steamcommunity.com/id/cirnoandcirno/
description: ...折返吧
favicon: favicon.png # Image must be in assets/images

url: https://atelier-icelf.github.io/ # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: atelier-icelf.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: 摸鱼部

  -
    href: /open-source
    label: 仓储部

  -
    href: /blog
    label: 统计部

  -
    href: /bookmark
    label: 画廊

  -
    href: /about
    label: 秘书室

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Photoshop,RpgMakerXP,RpgMkaerVXace,RpgMakerMV,AdobePremiere,Vegas]
skill_mobile_app_keywords: [摸鱼,扯淡,自闭,缝合怪本当上手]

# skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
# skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
# skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
# skill_mobile_app_keywords: [Android, Sketch UI Desgin]